### PR TITLE
More object-oriented registration model

### PR DESCRIPTION
**Pull request by annevk**
Here's a sketch. Someone should probably tweak it a bit more and make sure the language is consistent.

### CODE REVIEW

**Comment by annevk** [comment]
This is a sketch for #30 btw.

**Comment by jakearchibald** [comment]
This is great, although I think ID needs to be developer-set rather than generated, to allow:

```js
navigator.serviceWorker.ready.then(reg => {
  reg.syncManager.register("retry-email-send");
});
```

And in the worker:

```js
self.addEventListener('sync', event => {
  if (event.registration.id == 'retry-email-send') {
    event.waitUntil(...);
  }
  else if (event.registration.id == 'get-latest-news') {
    event.waitUntil(...);
  }
});
```

**Comment by annevk** [comment]
Yeah, that makes sense. So that would become a required argument again (and cause for rejection if already registered).

**Comment by jkarlin** [comment]
+1 to required argument. It forces the developer to think of the type of event and naturally coalesce around that. It does cause some pain if you want to set something like a calendar event which needs a unique name.

**Comment by clelland** [comment]
Could the sync id be optional -- the UA will use it if provided, and reject if already registered, but will auto-generate a unique ID if one isn't specified? It adds a bit of complication, but it at least enables the calendar use-case (and avoids having every developer write their own gensym code)

**Comment by annevk** [comment]
What is the calendar use case? Just having the need for one? Might be worth adding it to https://github.com/slightlyoff/BackgroundSync/blob/master/use-cases.md

**Pull request merged**
