### PR TITLE
Minor corrections to IDL

### PR DESCRIPTION
**Pull request by clelland**

### CODE REVIEW

**Comment by clelland** [comment]
DOMString would work, too -- I was looking for a definitive reference for which to use where (DOMString vs USVString), but didn't find one.

**Comment by clelland** [comment]
To be in line with the rest of SW (and issues like [crbug/432746](https://code.google.com/p/chromium/issues/detail?id=432746)), I think you're right. I'll change the PR.

**Comment by annevk** [comment]
It depends on whether serialization of the string to utf-8 needs to happen, basically.

**Comment by jkarlin** [comment]
annevk: So for the 'data' string, we would want USVString right? As we essentially want to support binary blobs.

**Comment by annevk** [comment]
Yeah, strings you store locally are not a concern, but if they go over the network you need to use USVString.

**Pull request merged**
